{"uuid": "86cd873c-7a24-46f7-84f1-ac31e1f35cac", "counter": 44, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'target_group' is undefined. 'target_group' is undefined\u001b[0m\r\n\u001b[0;31mfatal: [demo03]: FAILED! => {\"changed\": false, \"msg\": \"AnsibleUndefinedVariable: 'target_group' is undefined. 'target_group' is undefined\"}\u001b[0m", "start_line": 49, "end_line": 51, "runner_ident": "9ece7173-be05-493c-a80c-46e655b4f3fc", "event": "runner_on_failed", "pid": 201470, "created": "2025-05-16T00:41:44.822805+00:00", "parent_uuid": "005056b7-f67d-7f59-8438-000000000010", "event_data": {"playbook": "/tmp/tmp3x0zgvm0.yml", "playbook_uuid": "32116728-f180-4c80-939b-9e57fd9fe597", "play": "Configuraci\u00f3n de servidor web en Oracle Linux 9", "play_uuid": "005056b7-f67d-7f59-8438-000000000002", "play_pattern": "demo03", "task": "Copiar el archivo httpd.conf desde la plantilla", "task_uuid": "005056b7-f67d-7f59-8438-000000000010", "task_action": "template", "resolved_action": "ansible.builtin.template", "task_args": "", "task_path": "/tmp/tmp3x0zgvm0.yml:68", "host": "demo03", "remote_addr": "demo03", "res": {"msg": "AnsibleUndefinedVariable: 'target_group' is undefined. 'target_group' is undefined", "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ansible/template/__init__.py\", line 1001, in do_template\n    res = myenv.concat(rf)\n  File \"/usr/lib/python3.9/site-packages/ansible/template/native_helpers.py\", line 83, in ansible_concat\n    return ''.join([to_text(v) for v in nodes])\n  File \"/usr/lib/python3.9/site-packages/ansible/template/native_helpers.py\", line 83, in <listcomp>\n    return ''.join([to_text(v) for v in nodes])\n  File \"<template>\", line 21, in root\n  File \"/usr/lib/python3.9/site-packages/ansible/template/__init__.py\", line 262, in wrapper\n    ret = func(*args, **kwargs)\n  File \"/usr/lib/python3.9/site-packages/ansible/template/__init__.py\", line 525, in _ansible_finalize\n    return thing if _fail_on_undefined(thing) is not None else ''\n  File \"/usr/lib/python3.9/site-packages/ansible/template/__init__.py\", line 497, in _fail_on_undefined\n    elif is_sequence(data):\n  File \"/usr/lib/python3.9/site-packages/ansible/module_utils/common/collections.py\", line 94, in is_sequence\n    if not include_strings and is_string(seq):\n  File \"/usr/lib/python3.9/site-packages/ansible/_vendor/jinja2/runtime.py\", line 852, in _fail_with_undefined_error\n    raise self._undefined_exception(self._undefined_message)\njinja2.exceptions.UndefinedError: 'target_group' is undefined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/template.py\", line 141, in run\n    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)\n  File \"/usr/lib/python3.9/site-packages/ansible/template/__init__.py\", line 1035, in do_template\n    raise AnsibleUndefinedVariable(e, orig_exc=e)\nansible.errors.AnsibleUndefinedVariable: 'target_group' is undefined. 'target_group' is undefined\n", "_ansible_no_log": false, "changed": false}, "start": "2025-05-16T00:41:44.351895+00:00", "end": "2025-05-16T00:41:44.822299+00:00", "duration": 0.470404, "ignore_errors": null, "event_loop": null, "uuid": "86cd873c-7a24-46f7-84f1-ac31e1f35cac"}}